### ISSUE TITLE
blup cannot find key

### ISSUE THREAD

**Issue by rbutleriii** [cuelee/pleio#14]
Hi,

When running pleio with the `--blup` option, I get a KeyError that is missing "tausq"

log file:
```
************************************************************
* PLEIO(PLEIO)
* Version 2.0
* (C)2018 Cue H. Lee
* Seoul National University
* Unlicensed software
************************************************************
Call: 
./pleio.py \
--out pleio/all_simple \
--metain pleio/metain.txt.gz \
--sg pleio/sg.txt.gz \
--ce pleio/ce.txt.gz \
--create  \
--blup  \
--parallel  

Beginning analysis at Tue Mar  1 12:15:02 2022
Running PLEIO...
Writing PLEIO output file
Estimating BLUP...
Traceback (most recent call last):
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'tausq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rrbutler/opt/pleio/pleio.py", line 218, in <module>
    pleio(args,log)
  File "/home/rrbutler/opt/pleio/pleio.py", line 151, in pleio
    dat = data.sumstat.merge(res.loc[:,'tausq'], how = 'inner', left_index = True, right_index = True)
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1272, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1389, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1965, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/indexing.py", line 625, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/generic.py", line 3529, in xs
    return self[key]
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/scg/apps/software/anaconda/3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'tausq'

Analysis finished at Tue Mar  1 14:38:10 2022
Total time elapsed: 2h 23m 
```

**Comment by cuelee** [comment]
Hi rbutleriii,

Thank you for letting me know this. There seems to be a critical bug in the latest update. I'll be releasing an update to address this issue soon.

**Comment by rbutleriii** [comment]
Looks like it finished, but then errored writing to file:
```
Wrote tabulated inverse cdf
Running PLEIO...
Writing PLEIO output file
Estimating BLUP...
Analysis finished at Tue Mar 15 16:19:18 2022
Total time elapsed: 3m 
Traceback (most recent call last):
  File "/home/rrbutler/opt/pleio/pleio.py", line 218, in <module>
    pleio(args,log)
  File "/home/rrbutler/opt/pleio/pleio.py", line 155, in pleio
    blup_estimates.to_csv(self.output + '.blup.gz', index = True, sep ='\t', compression = 'gzip')
NameError: name 'self' is not defined
```

**Comment by cuelee** [comment]
I'm really sorry for the inconvenience. I just fixed the issue.
