### ISSUE TITLE
ValueError: --w-ld may only have one LD Score column.

### ISSUE THREAD

**Issue by Wubenrui** [cuelee/pleio#26]
Hi,
is there difference between '--w-ld-chr' and '--ref-ld-chr'? As the inputs of these two arguments in the example code are same (eur_w_ld_chr), I also pass ld score of reference to the '--w-ld-chr'. However, I got this error message:

Traceback (most recent call last):
  File "./ldsc_preprocess.py", line 482, in <module>
    preprocess(args,log)
  File "./ldsc_preprocess.py", line 349, in preprocess
    sumstat_data = generate_sumstat_data(data)
  File "./ldsc_preprocess.py", line 152, in __init__
    self.sumstats[trait] = self.h2_analysis(trait)
  File "./ldsc_preprocess.py", line 204, in h2_analysis
    sumstats.estimate_h2(h2_args, ldsc_h2_log)
  File "/home/wu_benrui/software/pleio/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/home/wu_benrui/software/pleio/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    w_ld = _read_w_ld(args, log)
  File "/home/wu_benrui/software/pleio/ldsc/ldscore/sumstats.py", line 136, in _read_w_ld
    raise ValueError('--w-ld may only have one LD Score column.')
ValueError: --w-ld may only have one LD Score column.

Could you help me with this?

**Comment by cuelee** [comment]
Dear Wubenrui,

Thank you for reaching out with your query. I found that the issue is related to  "[LDSC](https://github.com/bulik/ldsc)" To better understand the problem, could you please run the LDSC analysis directly with your data? This can be either heritability or co-heritability estimates. This will help determine if the error persists.

Once you have the results, let me know if the issue remains, and we can further investigate.

Best regards,
Cue Hyunkyu Lee
